/**
 * Emits `docs/catalogue.md` from the catalogue, so the browsable reference is derived rather than kept
 * in step by hand (T091).
 *
 * Run with no arguments to write the file; run with `--check` to verify the committed one matches, which
 * is the form wired into `pnpm check`. Adding a pattern is otherwise a complete and coherent change on
 * its own, and nothing would notice that a page describing the catalogue had stopped describing it.
 *
 * What this is *for* deserves stating, because a generated document is easy to write and easy to make
 * pointless. `describe_pattern` and `patterns describe` already answer everything here, authoritatively,
 * for one pattern at a time — so this is not the interface and must not become one. It is the page a
 * person reads before installing anything, to see whether the catalogue holds what they came for, and
 * the artefact a search engine can index. That is why it is a single file covering everything and why it
 * leads with the intents rather than the options.
 *
 * Everything rendered here comes from `describePattern`, which is the same call the two live surfaces
 * make. Reading the shards directly would be the shorter path and would let this page describe a
 * catalogue the engine does not agree it has — the reserved names are the clearest case, since they live
 * beside the templates that write them and only the describe path joins the two.
 */
import { readFile, mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import { describePattern as describeIn } from "../src/engine/catalog/describe.js";
import { listPatterns } from "../src/engine/catalog/list.js";
import { loadCatalog } from "../src/engine/catalog/load.js";

import type { PatternDetail } from "../src/engine/catalog/describe.js";
import type { Category } from "../src/engine/catalog/schema.js";

const OUTPUT_PATH = fileURLToPath(new URL("../docs/catalogue.md", import.meta.url));

/**
 * Category headings, in the order they appear on the page.
 *
 * Written here rather than taken from the schema's declaration order because this is an editorial
 * decision — what a reader should meet first — and the schema's order is an implementation detail of a
 * union. A category the schema gains and this omits is caught below rather than silently dropped.
 */
const CATEGORY_TITLES: Readonly<Record<Category, string>> = {
  "type-safety": "Type safety",
  "async-resilience": "Async resilience",
  "llm-orchestration": "LLM orchestration",
  "data-access": "Data access",
  structural: "Structural",
  behavioral: "Behavioural",
  creational: "Creational",
  functional: "Functional",
};

/**
 * @param directory An alternative shard directory, which exists so the guard can render a catalogue
 * containing shapes the shipped one does not — a legality rule, most importantly. Every pattern here
 * declares an empty `legality` array, so the branch that renders one would otherwise first run on the
 * day someone adds a rule, which is the wrong day to find out it renders badly.
 */
export async function render(directory?: string): Promise<string> {
  const catalog = await loadCatalog(directory);
  const details = listPatterns(catalog, {}).map((summary) => describeIn(catalog, summary.name));

  const generative = details.filter((detail) => detail.kind === "generative");
  const advisory = details.filter((detail) => detail.kind === "advisory");

  // Only the categories that have patterns in them, for the reason the skill's guard records: a heading
  // over nothing invites a reader to conclude the page is incomplete rather than the category empty.
  const populated = (Object.keys(CATEGORY_TITLES) as Category[]).filter((category) =>
    generative.some((detail) => detail.category === category),
  );

  const missing = [...new Set(generative.map((detail) => detail.category))].filter(
    (category) => !(category in CATEGORY_TITLES),
  );
  if (missing.length > 0) {
    throw new Error(
      `No heading for ${missing.join(", ")}. Add one to CATEGORY_TITLES in scripts/emit-docs.ts.`,
    );
  }

  const sections: string[] = [
    "<!-- Generated by scripts/emit-docs.ts. Run `pnpm docs:emit` after changing the catalogue. -->",
    "# Catalogue",
    `${String(generative.length)} generative patterns across ${String(populated.length)} categories, ` +
      `and ${String(advisory.length)} advisory entries that answer with what to write instead.`,
    "Every generative entry is emitted as complete TypeScript files that have been typechecked and " +
      "whose generated tests have been executed. This page is a reference to read before installing " +
      "anything; `patterns describe <name>` is the authority on what a given pattern accepts, and " +
      "cannot go stale.",
    contents(populated, generative, advisory),
  ];

  for (const category of populated) {
    sections.push(`## ${CATEGORY_TITLES[category]}`);
    for (const detail of generative.filter((entry) => entry.category === category)) {
      sections.push(generativeSection(detail));
    }
  }

  if (advisory.length > 0) {
    sections.push(
      "## Advisory entries",
      "These generate nothing, on purpose. TypeScript absorbed the problem each was solving, so asking " +
        "for one returns the modern construction and why — as a success, not an error.",
    );
    for (const detail of advisory) sections.push(advisorySection(detail));
  }

  return `${sections.join("\n\n")}\n`;
}

/** A table of contents, because a single page covering thirty-three entries is otherwise unnavigable. */
function contents(
  populated: readonly Category[],
  generative: readonly PatternDetail[],
  advisory: readonly PatternDetail[],
): string {
  const lines = populated.map((category) => {
    const names = generative
      .filter((detail) => detail.category === category)
      .map((detail) => `[${detail.name}](#${detail.name})`);
    return `- **${CATEGORY_TITLES[category]}** — ${names.join(", ")}`;
  });

  if (advisory.length > 0) {
    lines.push(
      `- **[Advisory](#advisory-entries)** — ${advisory.map((detail) => detail.name).join(", ")}`,
    );
  }

  return lines.join("\n");
}

function generativeSection(detail: PatternDetail): string {
  const parts: string[] = [`### ${detail.name}`, `**${detail.title}.** ${detail.intent}`];

  if (detail.identifiers.length > 0) {
    parts.push(
      `Names it generates around: ${detail.identifiers
        .map((role) => `\`${role.name}\` (${lower(role.description)})`)
        .join(", ")}.`,
    );
  }

  if (detail.reservedNames.length > 0) {
    // Included because it is the cheapest thing on this page to act on: a reader who learns here that
    // `Repository` is taken never spends a call finding out. Casing is stated because the refusal
    // compares derived names, so `repository` is the same collision (FR-052).
    const taken = detail.reservedNames.map((name) => `\`${name}\``).join(", ");
    parts.push(
      detail.reservedNames.length === 1
        ? `Writes ${taken} itself, so an identifier cannot be that name in any casing.`
        : `Writes ${taken} itself, so an identifier cannot be one of those in any casing.`,
    );
  }

  if (detail.network !== undefined) {
    // The reason is verbatim, as everything user-facing here is. Only the boundary and host are added,
    // since "it is injectable" is not actionable without the name of the thing to pass.
    const host =
      detail.network.defaultHost === undefined
        ? ""
        : `, and left alone it talks to \`${detail.network.defaultHost}\``;
    parts.push(
      `**Reaches the network.** ${detail.network.reason} Substitute at \`${detail.network.boundary}\`${host}.`,
    );
  }

  if (detail.options.length > 0) {
    // A list rather than a table. Option descriptions here run to a paragraph — that length is the point,
    // since it is what lets a caller choose without generating twice — and a table cell holding a
    // paragraph produces a column too wide to read on any width.
    parts.push(
      `**Options**\n\n${detail.options
        .map(
          (option) =>
            `- \`${option.name}\` — ${values(option)}, default ${defaultOf(option)}. ` +
            `${flatten(option.description)}`,
        )
        .join("\n")}`,
    );
  }

  if (detail.legality.length > 0) {
    // Verbatim, in the same words the refusal uses (FR-009). Rewording them here is how the explanation
    // a reader sees drifts from the constraint actually enforced.
    parts.push(
      `Refused rather than guessed at:\n${detail.legality
        .map((rule) => `- ${rule.rule} Instead: ${rule.alternatives.join(", ")}.`)
        .join("\n")}`,
    );
  }

  if (detail.relatedPatterns.length > 0) {
    parts.push(`Related: ${detail.relatedPatterns.map((name) => `\`${name}\``).join(", ")}.`);
  }

  return parts.join("\n\n");
}

function advisorySection(detail: PatternDetail): string {
  const advice = detail.advisory;
  if (advice === undefined) {
    throw new Error(`${detail.name} is advisory and carries no advisory content.`);
  }

  return [
    `### ${detail.name}`,
    `**${detail.title}.** Use ${advice.alternative} instead. ${advice.rationale}`,
    ...(advice.example === undefined ? [] : [`\`\`\`ts\n${advice.example}\n\`\`\``]),
  ].join("\n\n");
}

function values(option: PatternDetail["options"][number]): string {
  return option.type === "enum"
    ? option.values.map((value) => `\`${value}\``).join(" | ")
    : option.type === "boolean"
      ? "`true` | `false`"
      : option.type;
}

function defaultOf(option: PatternDetail["options"][number]): string {
  const shown = typeof option.default === "string" ? option.default : String(option.default);
  return shown === "" ? "—" : `\`${shown}\``;
}

/**
 * Collapses the newlines a shard uses to keep long prose readable in JSON.
 *
 * Needed because a bare newline inside a list item ends the item on some renderers, which would put the
 * rest of a description at the document's top level — a failure the emitter itself would report as
 * success, since the file it wrote is exactly the file it intended to write.
 */
function flatten(text: string): string {
  return text.replaceAll(/\s+/gu, " ").trim();
}

/** Lowercases a leading capital so a description reads as a clause inside a sentence. */
function lower(text: string): string {
  const trimmed = text.replace(/\.$/u, "");
  return trimmed.charAt(0).toLowerCase() + trimmed.slice(1);
}

async function main(): Promise<number> {
  const rendered = await render();
  const checkOnly = process.argv.includes("--check");

  if (!checkOnly) {
    await mkdir(fileURLToPath(new URL("../docs/", import.meta.url)), { recursive: true });
    await writeFile(OUTPUT_PATH, rendered, "utf8");
    return 0;
  }

  let committed: string;
  try {
    committed = await readFile(OUTPUT_PATH, "utf8");
  } catch {
    process.stderr.write("docs/catalogue.md is missing. Run `pnpm docs:emit` and commit the result.\n");
    return 1;
  }

  if (committed !== rendered) {
    process.stderr.write(
      "docs/catalogue.md is out of date with the catalogue.\n" +
        "Run `pnpm docs:emit` and commit the result.\n",
    );
    return 1;
  }

  return 0;
}

// Only when run, not when imported: the guard in `test/conformance/docs-page.test.ts` calls `render`, and
// a module that writes a file and sets an exit code on import would make importing it a side effect.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  process.exitCode = await main();
}
