/**
 * The provenance header (FR-020, FR-021).
 *
 * Two of these are about the header surviving the steps that come after it. It is emitted before
 * formatting so that the verified bytes are the returned bytes, which means Prettier and the comment
 * reflow pass both get a chance to rewrite it — and a header whose fields have been joined into a
 * paragraph is no longer machine-readable, which is the only reason it exists.
 */

import { describe, expect, it } from "vitest";

import { formatSource } from "../../src/engine/format/prettier.js";
import { generateBundle } from "../bundle.js";
import { optionsHash } from "../../src/engine/provenance/hash.js";
import {
  headerOf,
  renderHeader,
  withProvenance,
  withoutHeader,
} from "../../src/engine/provenance/header.js";

const request = {
  pattern: "result",
  options: { includeTests: false, includeAsync: false, includeCollections: false },
  identifiers: { entity: "Order" },
  variant: undefined,
};

describe("renderHeader", () => {
  it("carries the pattern and the options hash, and nothing else", () => {
    const header = renderHeader({ pattern: "result", optionsHash: "0123456789abcdef" });

    expect(header).toBe(
      [
        "/**",
        " * @generated by patterns — regenerate rather than edit.",
        " * @pattern result",
        " * @options 0123456789abcdef",
        " */",
        "",
        "",
      ].join("\n"),
    );
  });

  it("names no version, so a release cannot rewrite every generated file (FR-021)", () => {
    const header = renderHeader({ pattern: "result", optionsHash: "0123456789abcdef" });

    // The literal current versions, since a header carrying any of them is the failure being excluded.
    expect(header).not.toMatch(/\d+\.\d+\.\d+/);
    expect(header.toLowerCase()).not.toContain("version");
    expect(header.toLowerCase()).not.toContain("typescript");
    expect(header.toLowerCase()).not.toContain("prettier");
  });

  it("keeps every field on its own line after formatting at the default width", async () => {
    const source = `${renderHeader({ pattern: "result", optionsHash: "0123456789abcdef" })}export const x = 1;\n`;

    expect(await formatSource(source, {})).toContain(
      renderHeader({ pattern: "result", optionsHash: "0123456789abcdef" }),
    );
  });

  /**
   * The case that dictated the format. At 40 columns the reflow pass has to rewrap the header, and prose
   * would come back with the fields run together; `@tag` lines are separate paragraphs, so they survive
   * as separate lines whatever the width.
   */
  it("keeps every field on its own line at a width that forces a rewrap", async () => {
    const source = `${renderHeader({ pattern: "circuit-breaker", optionsHash: "0123456789abcdef" })}export const x = 1;\n`;

    const formatted = await formatSource(source, { printWidth: 40 });
    const lines = formatted.split("\n");

    expect(lines.filter((line) => line.includes("@pattern"))).toEqual([
      " * @pattern circuit-breaker",
    ]);
    expect(lines.filter((line) => line.includes("@options"))).toEqual([
      " * @options 0123456789abcdef",
    ]);
  });
});

describe("withProvenance", () => {
  it("heads every file, whatever its role (FR-020)", () => {
    const files = [
      { path: "a.ts", contents: "export const a = 1;\n", role: "core" as const },
      { path: "a.test.ts", contents: "export const b = 2;\n", role: "test" as const },
      { path: "a-example.ts", contents: "export const c = 3;\n", role: "example" as const },
    ];

    const headed = withProvenance(files, request);

    // Compared to each other rather than to a hash recomputed here: what this case is about is that a role
    // does not change the attribution, and recomputing the hash would restate the rule under test.
    for (const file of headed) {
      expect(headerOf(file.contents), `${file.path} is attributed for its role`).toBe(
        headerOf(headed[0]?.contents ?? ""),
      );
      expect(file.contents).toContain(" * @pattern result");
    }
  });

  /**
   * The one place a role does change the attribution, stated where the rule lives rather than only in the
   * conformance suite that found it. A split pattern's machinery is the half defined not to know the
   * caller's type, and it comes back with every `full` request — so hashing the entity into it made two
   * entities' requests disagree about a file they both install.
   */
  it("attributes a split pattern's machinery without the caller's type", () => {
    const split = { ...request, options: { ...request.options, emitScope: "full" } };

    const [core, binding] = withProvenance(
      [
        { path: "a-core.ts", contents: "export const a = 1;\n", role: "core" },
        { path: "order-a.ts", contents: "export const b = 2;\n", role: "binding" },
      ],
      split,
    );

    expect(headerOf(core?.contents ?? "")).not.toBe(headerOf(binding?.contents ?? ""));

    // And it is the entity that is absent, not something else: the same machinery asked for under another
    // entity is attributed identically.
    const other = withProvenance(
      [{ path: "a-core.ts", contents: "export const a = 1;\n", role: "core" }],
      { ...split, identifiers: { entity: "Invoice" } },
    );

    expect(headerOf(other[0]?.contents ?? "")).toBe(headerOf(core?.contents ?? ""));
  });

  /**
   * And only there. Nearly every pattern names its principal module `core`, so a rule keyed on the role
   * alone would have stripped the entity from the attribution of twenty-three patterns whose core *is* the
   * caller's type written out — claiming two different files came from one request.
   */
  it("attributes an unsplit pattern's core with the caller's type", () => {
    const core = { path: "order.ts", contents: "export const a = 1;\n", role: "core" } as const;

    const [order] = withProvenance([core], request);
    const [invoice] = withProvenance([core], { ...request, identifiers: { entity: "Invoice" } });

    expect(headerOf(order?.contents ?? "")).not.toBe(headerOf(invoice?.contents ?? ""));
  });

  it("leaves the rendered content otherwise untouched", () => {
    const contents = "export const a = 1;\n";
    const [file] = withProvenance([{ path: "a.ts", contents, role: "core" }], request);

    expect(withoutHeader(file?.contents ?? "")).toBe(contents);
  });
});

describe("withoutHeader", () => {
  it("strips a header this module wrote", () => {
    const contents = `${renderHeader({ pattern: "result", optionsHash: "0123456789abcdef" })}export const a = 1;\n`;

    expect(withoutHeader(contents)).toBe("export const a = 1;\n");
  });

  /**
   * The failure this guards against is silent rather than loud: a pattern of the form "strip the leading
   * block comment" would remove a template's own module documentation from a file that has no provenance
   * header, and the diff-stability harness would then be comparing something other than what it emits.
   */
  it("leaves a template's own leading documentation alone", () => {
    const contents = "/**\n * What this module is for.\n */\n\nexport const a = 1;\n";

    expect(withoutHeader(contents)).toBe(contents);
  });

  it("strips only the header, not documentation following it", () => {
    const header = renderHeader({ pattern: "result", optionsHash: "0123456789abcdef" });
    const documented = "/**\n * What this module is for.\n */\n\nexport const a = 1;\n";

    expect(withoutHeader(header + documented)).toBe(documented);
  });
});

describe("a generated bundle", () => {
  it("heads every file with its own request's hash", async () => {
    const bundle = await generateBundle({
      pattern: "result",
      identifiers: { entity: "Order" },
      options: { includeTests: true, includeAsync: false, includeCollections: false },
    });

    const expected = renderHeader({
      pattern: "result",
      optionsHash: optionsHash({
        pattern: "result",
        // `includeTests` is left out, as the header leaves it out: it decides which files exist rather
        // than what any of them says, so a suite that exists was asked for and one that does not cannot
        // be described. Including it meant a caller who regenerated without tests found every file they
        // kept re-attributed, identical code under a different hash.
        options: { ...bundle.resolvedOptions, includeTests: undefined },
        identifiers: { entity: "Order" },
        variant: undefined,
      }),
    });

    expect(bundle.files.length).toBeGreaterThan(1);
    for (const file of bundle.files) {
      expect(file.contents).toContain(expected);
    }
  });

  /**
   * The two halves of that exclusion, since either alone is satisfiable by a header that says too little or
   * too much: declining the suite must not move the attribution of a file that survives, and an option that
   * shapes the code must.
   */
  it("heads a file the same whether or not tests were asked for", async () => {
    const [withTests, without] = await Promise.all([
      generateBundle({ pattern: "result", identifiers: { entity: "Order" }, options: { includeTests: true } }),
      generateBundle({ pattern: "result", identifiers: { entity: "Order" }, options: { includeTests: false } }),
    ]);

    const kept = without.files.map((file) => file.path);
    expect(kept.length, "nothing survives declining the suite, so this case tests nothing").toBeGreaterThan(
      0,
    );

    for (const path of kept) {
      expect(
        headerOf(withTests.files.find((file) => file.path === path)?.contents ?? ""),
        `${path} is attributed differently for having been asked for beside a suite`,
      ).toBe(headerOf(without.files.find((file) => file.path === path)?.contents ?? ""));
    }
  });

  /**
   * The hash covers the *resolved* request, so a caller who states a default explicitly gets the same
   * header as one who omits it. Anything else would make the header report how a request was phrased
   * rather than what it asked for.
   */
  it("heads identically-resolving requests identically", async () => {
    const [omitted, stated] = await Promise.all([
      generateBundle({ pattern: "result", identifiers: { entity: "Order" } }),
      generateBundle({
        pattern: "result",
        identifiers: { entity: "Order" },
        options: { includeAsync: true },
      }),
    ]);

    expect(headerOf(stated.files[0]?.contents ?? "")).toBe(headerOf(omitted.files[0]?.contents ?? ""));
  });

  it("heads materially different requests differently", async () => {
    const [withAsync, without] = await Promise.all([
      generateBundle({
        pattern: "result",
        identifiers: { entity: "Order" },
        options: { includeAsync: true },
      }),
      generateBundle({
        pattern: "result",
        identifiers: { entity: "Order" },
        options: { includeAsync: false },
      }),
    ]);

    expect(headerOf(withAsync.files[0]?.contents ?? "")).not.toBe(
      headerOf(without.files[0]?.contents ?? ""),
    );
  });
});
